version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.6.37
        environment:
          MYSQL_DATABASE: workflow_example
          MYSQL_ROOT_PASSWORD: password

    working_directory: ~/app

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-

      - run: cat /dev/null | sbt clean test:compile

      - save_cache:
          paths:
            - "~/.m2"
            - "~/.ivy2"
            - "~/.sbt"
            - "~/.cache/coursier"
            - "lib_managed"
            - "target"
            - "project/target"
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run:
          name: sbt test
          command: |
             cp conf/database.flyway.test.conf conf/database.flyway.conf
             sbt flywayMigrate test
